name: flutter_alarm_clock
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

  #pub.dev packages
  sqflite: ^2.0.2+1
  flutter_local_notifications: ^16.2.0
  dotted_border: ^2.0.0+2
  provider: ^6.0.3
  intl: ^0.18.1
  alarm: ^3.0.0-dev.4

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/mozart.mp3
    - assets/nokia.mp3
    - assets/one_piece.mp3
    - assets/star_wars.mp3
    - assets/marimba.mp3
    - assets/add_alarm.png
    - assets/alarm_icon.png
    - assets/clock_icon.png
    - assets/timer_icon.png
    - assets/stopwatch_icon.png
  fonts:
    - family: avenir
      fonts:
        - asset: assets/fonts/Avenir-Book.ttf
        - asset: assets/fonts/Avenir-Heavy.ttf
          weight: 700
        - asset: assets/fonts/Avenir-Medium.ttf
          weight: 500
        - asset: assets/fonts/Avenir-Light.ttf
          weight: 300
